from config import *


#SERVER
SERVER_ADDRESS = "2001::22"
SERVER_PORT = 21570

#SE 1 ENVIA O PACOTE, SE 0 PRINTA NA TELA
SEND_PACKET_TO_NETWORK = 1


#ETHERNET
#SEND FROM CLIENT TO SERVER
#MAC_SOURCE  = PC1_MAC
#MAC_DESTINO = PC2_MAC

MAC_SOURCE  = PC2_MAC
MAC_DESTINO = PC1_MAC

#IPv6

#SEND FROM CLIENT TO SERVER
#IP_SRC  = PC1_IP_HEX
#IP_DEST = PC2_IP_HEX

#SEND FROM SERVER TO CLIENT
IP_SRC  = PC2_IP_HEX
IP_DEST = PC1_IP_HEX
IPV6_FLOW_LABEL = "0b2605"


#PORTA SERVER = 5442

#TCP
TCP_DATA = ""

SRC_PORT = "5442"
DEST_PORT = "90be"

SEQ_NO = "21fdb111"
ACK_NO = "8afdebbd"
CHECK_SUM = "293a"

TCP_WINDOW_SIZE = "00e1" #"00e1" 

OPTIONS = "0101080a00316e9800316e98"

PUSH_FLAG = 0
ACK_FLAG = 1
RST_FLAG = 0
SYN_FLAG = 0
FIN_FLAG = 1




#FIX MAC
MAC_DESTINO = MAC_DESTINO.replace(":", "")
MAC_SOURCE = MAC_SOURCE.replace(":", "")